export const courses = [
  {
    id: 'english',
    name: 'Ingliz tili',
    slug: 'ingliz-tili',
    emoji: '🇬🇧',
    icon: 'globe',
    color: 'orange',
    shortDesc: 'Umumiy kurslar, intensiv format va IELTS tayyorlov — har qadamda monitoring va individual yondashuv.',
    fullDesc: `Ingliz tili kursi A School'da eng mashhur va talab qilinadigan yo'nalishlardan biridir. Biz o'quvchilarni nafaqat grammatika va lug'at bilan, balki real muloqot, tinglab tushunish va yozish ko'nikmalari bilan qurollantiramiz.`,
    levels: [
      { name: 'Umumiy kurs', desc: 'Boshlang\'ich va o\'rta darajalar uchun. Hafta 3 kun, oyda 12 soat.', price: '360 000', duration: '3–6 oy' },
      { name: 'Intensiv kurs', desc: 'Tezlashtirilgan format. Har kuni dars, chuqur o\'rganish.', price: '560 000', duration: '2–4 oy' },
      { name: 'IELTS tayyorlov', desc: 'Band 6.0–7.5 maqsad. Speaking, Writing, Listening, Reading.', price: '530 000', duration: '3–6 oy' },
    ],
    features: [
      'Native-style speaking sessions',
      'Real IELTS mock testlar',
      'Haftalik progress hisoboti',
      'Kichik guruhlar (max 10 kishi)',
      'Online materiallar kiritilgan',
    ],
    teachers: ['5+ yillik tajriba', 'IELTS 7.5+ sertifikat'],
    chips: ['Umumiy', 'Intensiv', 'IELTS'],
    priceRange: '360 000 – 560 000',
  },
  {
    id: 'russian',
    name: 'Rus tili',
    slug: 'rus-tili',
    emoji: '🇷🇺',
    icon: 'flag',
    color: 'orange',
    shortDesc: 'Kommunikativ yondashuv va amaliy mashg\'ulotlar — kundalik hayot va ish uchun.',
    fullDesc: `Rus tili kursi zamonaviy kommunikativ metodologiya asosida qurilgan. O'quvchilar birinchi kundan boshlab rus tilida gaplashishga o'rgatiladi, grammatika esa amaliyot orqali o'zlashtiriladi.`,
    levels: [
      { name: 'Standart kurs', desc: 'Barcha darajalar uchun. Hafta 3 kun, oyda 12 soat.', price: '360 000', duration: '4–8 oy' },
    ],
    features: [
      'Kommunikativ metodologiya',
      'Rol o\'yinlari va dialog mashqlari',
      'Fonetika va talaffuz ishlash',
      'Kichik guruhlar',
      'Dars materiallar bepul',
    ],
    teachers: ['Rus tili filologiyasi mutaxassislari'],
    chips: ['Standart', '12 soat/oy'],
    priceRange: '360 000',
  },
  {
    id: 'korean',
    name: 'Koreys tili',
    slug: 'koreys-tili',
    emoji: '🇰🇷',
    icon: 'flag',
    color: 'purple',
    shortDesc: 'Oddiy kurs va TOPIK imtihoniga chuqur tayyorlov. K-madaniyat orqali qiziqarli o\'rganish.',
    fullDesc: `Koreys tili kursi A School'da eng qiziqarli yo'nalishlardan biri. Hangul alifbosidan boshlab TOPIK imtihonigacha bo'lgan to'liq yo'l. K-drama, K-pop va madaniyat orqali til o'rganish jarayoni qiziqarli va samarali bo'ladi.`,
    levels: [
      { name: 'Standart kurs', desc: 'Hangul, asosiy so\'z boyligi, grammatika.', price: '360 000', duration: '4–8 oy' },
      { name: 'TOPIK tayyorlov', desc: 'TOPIK I va TOPIK II imtihonlariga tayyorlov.', price: '400 000', duration: '3–6 oy' },
    ],
    features: [
      'Hanguldan TOPIK gacha',
      'K-madaniyat elementlari',
      'Original Korean media ishlatiladi',
      'TOPIK mock testlar',
      'Haftalik lug\'at test',
    ],
    teachers: ['TOPIK 4–5 darajali o\'qituvchilar'],
    chips: ['Standart', 'TOPIK'],
    priceRange: '360 000 – 400 000',
  },
  {
    id: 'it',
    name: 'IT / Dasturlash',
    slug: 'it-dasturlash',
    emoji: '💻',
    icon: 'code',
    color: 'orange',
    shortDesc: 'Boshlang\'ich va o\'rta daraja — real loyihalar, amaliy kodlash, zamonaviy texnologiyalar.',
    fullDesc: `IT kursi A School'da eng istiqbolli yo'nalishdir. Boshlang'ichlar uchun HTML/CSS/JS asoslaridan boshlab, o'rta darajalar uchun React va backend texnologiyalargacha. Har bir o'quvchi kurs oxirida portfolio loyiha yaratadi.`,
    levels: [
      { name: 'Boshlang\'ich daraja', desc: 'HTML, CSS, JavaScript asoslari. Portfolio: 3 ta web sahifa.', price: '480 000', duration: '4–6 oy' },
      { name: 'O\'rta daraja', desc: 'React, Node.js, ma\'lumotlar bazasi asoslari.', price: '480 000', duration: '4–6 oy' },
    ],
    features: [
      'Real loyihalar bilan ishlash',
      'GitHub portfolio yaratish',
      'Code review sessiyalar',
      'Zamonaviy texnologiyalar',
      'Ish topishda yordam',
    ],
    teachers: ['Sanoatda ishlaydigan dasturchilar'],
    chips: ['Boshlang\'ich', 'O\'rta daraja'],
    priceRange: '480 000',
  },
  {
    id: 'media',
    name: 'Media yo\'nalishi',
    slug: 'media',
    emoji: '🎥',
    icon: 'video',
    color: 'purple',
    shortDesc: 'Mobilografiya, kontent, video ishlov. Yaqinda: SMM, target, blogging, talaffuz — full paket.',
    fullDesc: `Media yo'nalishi A School'ning eng trendy va zamonaviy kursi. Smartphone bilan professional kontent yaratishdan boshlab to SMM strategiyasi va targetgacha. Bloggerlar, kontent-kreatorlar va SMM mutaxassislari uchun ideal.`,
    levels: [
      { name: 'Mobilografiya & Kontent', desc: 'Telefon bilan professional foto va video olish.', price: 'TBA', duration: '2–3 oy' },
      { name: 'Full Media Paket', desc: 'SMM, target, blogging, talaffuz. Yaqinda ochiladi.', price: 'TBA', duration: '4–6 oy' },
    ],
    features: [
      'Smartphone videografiya',
      'Kontent rejalashtirish',
      'Video montaj asoslari',
      'Instagram/TikTok optimizatsiya',
      'Brend storytelling',
    ],
    teachers: ['Faol media mutaxassislari'],
    chips: ['Kontent', 'Video', 'SMM'],
    priceRange: 'TBA',
    comingSoon: true,
  },
  {
    id: 'chemistry',
    name: 'Kimyo & Biologiya',
    slug: 'kimyo-biologiya',
    emoji: '🧪',
    icon: 'flask',
    color: 'orange',
    shortDesc: 'Abituriyentlar uchun chuqur tayyorlov. DTM imtihoniga yo\'naltirilgan, fan asoslaridan amaliyotgacha.',
    fullDesc: `Kimyo va Biologiya kurslari abituriyentlarga DTM imtihoniga to'liq tayyorgarlik ko'rish imkonini beradi. Har bir mavzu nazariyadan amaliy mashqlargacha chuqur o'rganiladi. Test yechish strategiyalari ham o'rgatiladi.`,
    levels: [
      { name: 'DTM tayyorlov (Kimyo)', desc: 'DTM kimyo testlarini yechish strategiyasi va chuqur bilim.', price: 'Bog\'laning', duration: '6–12 oy' },
      { name: 'DTM tayyorlov (Biologiya)', desc: 'DTM biologiya testlari uchun to\'liq kurs.', price: 'Bog\'laning', duration: '6–12 oy' },
    ],
    features: [
      'DTM format testlar',
      'Har hafta mock imtihon',
      'Zaif tomonlarni tahlil qilish',
      'Individual darslar mavjud',
      'O\'tgan yillar testlari',
    ],
    teachers: ['Oliy ta\'lim muassasalari bitiruvchilari'],
    chips: ['Kimyo', 'Biologiya', 'DTM'],
    priceRange: 'Bog\'laning',
  },
]

export const getCourseBySlug = (slug) => courses.find(c => c.slug === slug)
